server:
  port: 8002
spring:
  application:
    name: edu-course-boot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.141:3306/edu_course?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123123
  redis:
    host: 192.168.249.81
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
